### ISSUE TITLE
Mover arquivos de language/english/files e language/portuguese/arquivos

### ISSUE THREAD

**Issue by lianestellet** [pugpe/meetup-cookbook#20]
As pastas **languages/english** e **languages/portuguese** só possuem um arquivo .md, não seria interessante remover pastas extras alterando o local dos arquivos?

- Mover os arquivos que estão em: 
meetup-cookbook/languages/english/files
para:
meetup-cookbook/languages/english/

- Mover os arquivos que estão em: 
meetup-cookbook/languages/portuguese/arquivos
para:
meetup-cookbook/languages/portuguese/

- Atualizar referências do seu arquivo de tradução, caso tenha

**Comment by naanadr** [comment]
Olá.

Então a organização foi pensada como cada idioma que tem dentro do `languages` fosse um projeto a parte. E dentro do diretório `files` ou `arquivos` ficam os arquivos que vão sendo usados no cookbook, pra não ficar desorganizado, se deixar o `CONTRIBUTING.md` no mesmo diretório, talvez acabe ficando meio desorganizado.

**Comment by lianestellet** [comment]
@naanadr como pretendem manter a estrutura assim estarei fechando essa Issue :)
