### ISSUE TITLE
Adicionar tradução para o Contributing.en.md

### ISSUE THREAD

**Issue by lianestellet** [pugpe/meetup-cookbook#21]
Alterar idioma do português para o inglês no arquivo languages/english/Contributing.en.md.

**Comment by naanadr** [comment]
Não está como prioridade agora adicionar a tradução.
Mas caso você queira ajudar nessa parte de tradução, adoraríamos ter mais uma pessoa contribuindo. :)  

Porque, estamos precisamos antes terminar a parte inicial do cookbook, acabamos só fazendo a parte da `organização no dia`.
